version: 1.0.{build}
image: WMF 5
branches:
  only:
  - release
environment:
  PsGalleryKey:
    secure: fwGMwHl4zwLum9NAgMiTZARUPEa/9G83BpX3dTCTskZMmoqi9padKBk1mTVgm2Xs
build_script:
- ps: Publish-Module -Path . -NuGetApiKey $env:PsGalleryKey